
[_LAYER0] = LAYOUT
(KC_TAB, KC_Q, KC_W, KC_F, KC_P, KC_G, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_BSPC, 
KC_LCTL, KC_A, KC_R, KC_S, KC_T, KC_D, KC_H, KC_N, KC_E, KC_I, KC_O, KC_QUOT, 
KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_K, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_ESC, 
                KC_LALT, MO(1), KC_ENT, KC_SPC, MO(2), KC_RALT),

[_LAYER1] = LAYOUT
(KC_ESC, KC_MPRV, KC_UP, KC_MNXT, KC_PSCR, KC_EXEC, KC_PGUP, KC_1, KC_2, KC_3, KC_PAUS, KC_DEL, 
KC_LCTL, KC_LEFT, KC_DOWN, KC_RGHT, KC_ENT, KC_INS, KC_HOME, KC_4, KC_5, KC_6, KC_0, KC_END, 
KC_LSFT, KC_F13, KC_CAPS, KC_CALC, KC_F14, KC_MPLY, KC_PGDN, KC_7, KC_8, KC_9, KC_NO, KC_FIND, 
                KC_LALT, KC_TRNS, KC_ENT, KC_RCTL, MO(3), RALT(KC_ENT)),

[_LAYER2] = LAYOUT
(KC_ESC, KC_GRV, KC_CIRC, KC_PERC, KC_EXLM, KC_LPRN, KC_RPRN, KC_PEQL, KC_ASTR, KC_NO, KC_PIPE, KC_DEL, 
KC_LCTL, KC_AT, KC_DLR, KC_LT, KC_MINS, KC_LBRC, KC_RBRC, KC_PLUS, KC_GT, KC_AMPR, KC_NO, KC_BSLS, 
KC_LSFT, KC_NO, KC_NO, RALT(KC_K), KC_HASH, KC_LCBR, KC_RCBR, KC_NO, RALT(KC_5), KC_UNDS, KC_EXLM, KC_ENT, 
                KC_LGUI, MO(3), CW_TOGG, KC_SPC, KC_TRNS, KC_RALT),

[_LAYER3] = LAYOUT
(KC_NO, TO(5), KC_NO, KC_NO, TO(4), TO(9), TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, 
KC_PDOT, KC_P1, KC_P2, KC_P3, KC_P4, KC_P5, KC_P6, KC_P7, KC_P8, KC_P9, KC_P0, KC_PENT, 
                KC_NO, KC_TRNS, KC_NO, TO(4), KC_TRNS, KC_NO),

[_LAYER4] = LAYOUT
(RGB_TOG, RGB_MOD, RGB_SAI, RGB_HUI, RGB_SPI, RGB_VAI, BL_UP, KC_NO, KC_NO, KC_NO, KC_NO, BL_ON, 
KC_NO, RGB_RMOD, RGB_SAD, RGB_HUD, RGB_SPD, RGB_VAD, BL_DOWN, BL_TOGG, BL_STEP, BL_BRTG, KC_NO, BL_OFF, 
KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, EE_CLR, QK_BOOT, 
                KC_NO, KC_NO, TO(0), KC_TRNS, KC_NO, KC_NO),

[_LAYER5] = LAYOUT
(KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC, 
KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, 
KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_ESC, 
                KC_LALT, MO(1), KC_ENT, KC_SPC, MO(2), KC_RALT),

[_LAYER6] = LAYOUT
(KC_TAB, KC_Q, KC_W, KC_E, KC_T, KC_Y, RCS(KC_ESC), KC_NO, KC_NO, KC_NO, KC_NO, LCA(KC_DEL), 
KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, TO(0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
                KC_LALT, MO(7), KC_SPC, KC_NO, KC_NO, KC_RGUI),

[_LAYER7] = LAYOUT
(KC_ESC, KC_I, KC_UP, KC_M, KC_L, KC_O, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
KC_LCTL, KC_LEFT, KC_DOWN, KC_RGHT, KC_ENT, KC_P, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
KC_LSFT, KC_1, KC_2, KC_3, KC_4, KC_5, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, 
                KC_NO, KC_TRNS, KC_NO, KC_NO, TO(0), KC_NO) 



