NKRO_ENABLE = yes
RGBLIGHT_ENABLE = no   # Enable WS2812 RGB underlight.
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes
DEBOUNCE_TYPE = sym_eager_pk
CAPS_WORD_ENABLE = yes
TAP_DANCE_ENABLE = yes
SRC += features/select_word.c

KEY_OVERRIDE_ENABLE = yes

# Size optimization
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESCAPE_ENABLE = no
MOUSEKEY_ENABLE = no
MAGIC_ENABLE = no
AUDIO_ENABLE = no
MUSIC_ENABLE = no